### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by benswinburne** [dsifford/yarn-completion#13]
It'd be nice to be able to install this using homebrew if possible.

**Comment by dsifford** [comment]
I'll look into it when I get some extra time

**Comment by benswinburne** [comment]
Nice one, thanks very much!

**Comment by dsifford** [comment]
Doesn't appear like adding support for this would be allowed per the [homebrew guidelines](https://docs.brew.sh/Acceptable-Formulae).

@benswinburne If you'd really like to see this land in homebrew, perhaps consider reaching out to the maintainers of the yarn formula and see if they can add it as an optional dependency.

**Comment by kachkaev** [comment]
@dsifford which particular rule in the guidelines do you find difficult to adhere? There are quite a few similar automcompletion formulae in homebrew already:

<img width="650" alt="screen shot 2018-03-08 at 18 28 39" src="https://user-images.githubusercontent.com/608862/37169042-af7f6628-22fe-11e8-996d-76db6a725b8b.png">

**Comment by dsifford** [comment]
The rule stating that new formulae must have an accompanying website

**Comment by dsifford** [comment]
@kachkaev I'll check out those formulae when I get some time. Technically, if I'm reading the guidelines correctly, those shouldn't be allowed to exist. But if they're letting those slide, I suppose they'd have to let this one slide too...

**Comment by kachkaev** [comment]
👍 

I'm quite sure they will accept your brew formulae @dsifford! Yarn is a very popular tool these days and your repo seems to be pretty much the only yarn autocompletion that exists! I wish you be the first who claims `yarn-completion` package name in Homebrew!

**Comment by jasonkarns** [comment]
https://github.com/Homebrew/homebrew-core/pull/28645

**Comment by jasonkarns** [comment]
Sooo... issue...

In order to accepted into homebrew, the formula is supposed to have a non trivial test. I'm using the same test as for other completion scripts currently in homebrew (rails, vagrant), which sources the completion script, runs `complete -p yarn`, and verifies the output is as expected.

Wrinkle: the homebrew tests are run on travis CI using macOS which uses the 3.2 version of bash.

I realize that 3.2 support is already out of the question, but would it be possible to at least make _sourcing_ on 3.2 succeed so the brew tests can pass?

**Comment by dsifford** [comment]
Sure. Start a PR and I'd be happy to merge if everything works and checks out.

**Comment by jasonkarns** [comment]
PR here: https://github.com/dsifford/yarn-completion/pull/18

**Comment by jasonkarns** [comment]
Thanks for merging #18. I believe all we need is a new release (brew formulae need to point to specific versions) and we can get this into homebrew!

**Comment by dsifford** [comment]
Sure, I'll do that in a bit.

Does homebrew have any notion of dependencies between formulae? If possible, to avoid the headache, could we make the package dependent on bash 4?

**Comment by jasonkarns** [comment]
Having that discussion now on the brew PR. If we declare bash as a dep (which would imply the v4 bash from homebrew itself), it would actually _install_ bash as part of installing yarn-completion. Which would be a bad experience. (Installing yarn-completion and getting an entirely new shell?)

Perhaps it can be noted as a recommended dep? Unsure, still investigating (and checking other completion scripts in homebrew.)

**Comment by dsifford** [comment]
Sounds good. Keep us posted.

Just pushed a release: https://github.com/dsifford/yarn-completion/releases/tag/v0.7.4

**Comment by dsifford** [comment]
Apparently a kind samaritan already went and tackled this back in August. 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn-completion.rb

Closing this as resolved. Thanks @DomT4! 🎉

**Comment by jasonkarns** [comment]
yep! i opened https://github.com/Homebrew/homebrew-core/pull/28645 and it was merged beginning of August.

homebrew PR was noted here: https://github.com/dsifford/yarn-completion/issues/13#issuecomment-394520474

**Comment by dsifford** [comment]
@jasonkarns is this set to track off of github releases or does someone need to manually go in and update? If the latter, I'll try and make a mental note to do that.

**Comment by jasonkarns** [comment]
Needs to be manually updated via a PR similar to: https://github.com/Homebrew/homebrew-core/commit/4f418e6d91664f07ec992a6e35206ab08870b6f7

However, homebrew has a command that can automate the PR creation process: `brew bump-formula-pr`

**Comment by jasonkarns** [comment]
I can open a PR to set up a similar release process here if you like.

**Comment by dsifford** [comment]
Sounds lovely. Thanks :+1:

**Comment by dsifford** [comment]
Just pushed a release @jasonkarns --- what do I do now?

**Comment by jasonkarns** [comment]
Well, short story (because I haven't gotten the scripts PR open for you yet)...

```
HOMEBREW_DEVELOPER=true brew bump-formula-pr --url="https://github.com/dsifford/yarn-completion/archive/v0.9.0.tar.gz" --sha256="$(curl -fsSL "https://github.com/dsifford/yarn-completion/archive/v0.9.0.tar.gz" | shasum -a 256 -b | awk '{print $1}')" yarn-completion
```

That should make the branch in your brew git repo, create a homebrew fork for you (if you don't already have one), push the branch to your fork, and open a PR to bump the formula version.

You can also add a `--dry-run` flag to the brew command if you want to see what it'll do.

**Comment by dsifford** [comment]
All set https://github.com/Homebrew/homebrew-core/pull/32637

Thanks
