### ISSUE TITLE
Doesn't work on Mac with bash 3

### ISSUE THREAD

**Issue by fobdy** [dsifford/yarn-completion#17]
Tab key with yarn string triggers an error after yarn completion installed.

Error:
```
-bash: compopt: command not found
-bash: compopt: command not found
-bash: compopt: command not found
```

```
OS version: macOS High Sierra 10.13.4

Bash version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

Yarn version: 1.7.0
Node version: 9.9.0
```

**Comment by dsifford** [comment]
Known issue. 

I don't have the time, energy, or desire to support a 9 year outdated version of bash. Simply upgrade to the latest bash version and your life will be easier for reasons far beyond just autocompletion.
