### ISSUE TITLE
Feature request: support workspaces whose names do not match their directory names

### ISSUE THREAD

**Issue by Infiltrator** [dsifford/yarn-completion#26]
packages.json:
```JSON
{
  "workspaces": [
    "packages/*"
  ]
}
```

packages/bar/package.json:
```JSON
{
  "name": "@foo/bar"
}
```

Trying completion:
`yarn workspace @foo/bar <TAB>` or `yarn workspace bar <TAB>` gives completion for the root `package.json` instead.

**Comment by dsifford** [comment]
Thanks for the feedback.

Unfortunately, this is not reasonably possible using only posix-compliant bash. This would only be feasible to add if I were able to use something that could parse JSON but, in order to keep this cross-platform and dependency free, I don't have that luxury.

**Comment by Infiltrator** [comment]
So if there were bash code that could parse JSON, you would be willing to include it?  Would it need to be a full JSON parser or just enough to read `{ "name": "@foo/bar" }` out?
