### ISSUE TITLE
use package name instead of directory basename for workspace

### ISSUE THREAD

**Issue by n1ru4l** [dsifford/yarn-completion#29]
I think this are the relevant lines:
https://github.com/dsifford/yarn-completion/blob/f0d517043b7f6d4244b82d57c0a28cacc5d0d08d/yarn-completion.bash#L905

The package name of a workspace package is not always equal to the folder name. E.g. a scoped package `@organisation/foobar` could be located under `packages/foobar`.

`yarn-completion` only completes with `foobar` instead of `@organisation/foobar`.

Therefore `yarn-completion` should rely on parsing the package name from the actual `package.json` of the workspace package.

**Comment by dsifford** [comment]
Good point. I'll look into getting this fixed as soon as I get some free time. PRs accepted also.
