### ISSUE TITLE
Colon-contained completion glitches

### ISSUE THREAD

**Issue by takuyahara** [dsifford/yarn-completion#34]
When I type a text that contains colon(`:`) and push tab to complete result glitches like this.

```terminal
$ yarn test # push tab key
$ yarn test:e2e # ok, this is expected

$ yarn test: # push tab key
$ yarn test:test:e2e # completed text comes after colon
```

* macOS 10.14.3
* bash 5.0.3

**Comment by dsifford** [comment]
My laptop is running the same OS and bash version as you list and I don't have this issue. Could be an issue with your bash initialization and/or shell options. Hard to know for sure.

**Comment by takuyahara** [comment]
Thank you for your hint! I found the solution here.
https://gist.github.com/stecman/6cc2769b135f272b673a#file-bash_completion_fill-sh-L194
