### ISSUE TITLE
Tests fail on latest yarn

### ISSUE THREAD

**Issue by ObserverOfTime** [dsifford/yarn-completion#40]
```  
======================================================================
Environment checks
======================================================================
  should match yarn version line in src file....................FAILED
  | ERROR: mismatched yarn version line in src file.
  | 
  | expected: 1.19.1
  | received: 1.17.3
```
If there isn't anything else that needs to be changed, I can submit a PR to update the version number.

**Comment by dsifford** [comment]
Looks like it's just the version number that needs updating. 

> If there isn't anything else that needs to be changed, I can submit a PR to update the version number.

Sure, that'd be awesome. Thanks.
