### ISSUE TITLE
Yarn v2/berry support ?

### ISSUE THREAD

**Issue by gluck** [dsifford/yarn-completion#49]
Yarn v1 being on maintenance mode, it'd be great to support the upcoming v2/berry.

Food for thoughts:
- command list is pretty different
- yarn version is "per-repository"
- the script could either detect the current yarn version to provide proper completion
- or create another branch/script and rely on the user to use the proper one ?

[`yarn --help`](https://github.com/dsifford/yarn-completion/files/4830441/yarn.txt)

**Comment by dsifford** [comment]
Hi @gluck. I've had this in the back of my mind for a while, but I honestly think that v2 is so drastically different than v1 that it would need its own implementation separate from this one.

I don't use v2 personally and don't have much free time these days so I don't think I will be the one to put those together.

I would have loved it if the yarn folks would have supported this on their end. That would be the ideal scenario.

**Comment by gluck** [comment]
Yes, I also think there's only so much you can do on a separate shell script, first class support inside yarn itself would be preferable.
Thanks for the feedback, not sure I'll be the one to pick this task up either.

**Comment by devthejo** [comment]
here is the fix for `yarn workspace` completion for v2/v3: https://github.com/dsifford/yarn-completion/pull/54
;)
