### ISSUE TITLE
Incorrect suggestion with script name with colon :

### ISSUE THREAD

**Issue by ghost** [dsifford/yarn-completion#55]

**Comment by ChromeQ** [comment]
I have some scripts in my package.json which contain the `:` character, this is common for commands such as `build:dev` or `build:prod` and `lint:fix` or `lint:errors` but this bash script will not complete the command when pressing tab key after the `:`

Example:
package.json with several scripts with colon:
![image](https://github.com/dsifford/yarn-completion/assets/75962642/25442a83-f925-40bb-8f25-9c599f4f1733)

type the start of a script name and hit tab:
![image](https://github.com/dsifford/yarn-completion/assets/75962642/e0bec6ba-8071-48dd-b39c-797c4bcbd32b)

my choices are `expo:prebuild` or `expo:preview` so it's good to check in with me which to autocomplete, type the b character for prebuild and press tab again:
![image](https://github.com/dsifford/yarn-completion/assets/75962642/a4a1c489-9ea0-493a-a864-34c774fbe9cf)

My bash skills are not good enough to tackle this myself so I'm hoping you can do a quick fix or suggest something as it works for the npm-completion script. Thanks
