### ISSUE TITLE
Getting error _yarn:82: command not found: _get_comp_words_by_ref in zsh

### ISSUE THREAD

**Issue by duro** [dsifford/yarn-completion#8]
Followed instructions for ZSH installation and any tab completion throws that error

```
_yarn:82: command not found: _get_comp_words_by_ref
```

**Comment by dsifford** [comment]
@duro Can you try changing [these lines](https://github.com/dsifford/yarn-completion/blob/master/yarn-completion.bash#L543-L547) to the following and let me know if that works?

```sh
if command -v _init_completion >/dev/null; then
    _init_completion
else
    if [ ! "$ZSH_NAME" ]; then
        _get_comp_words_by_ref cur prev words cword
    fi
fi
```

**Comment by DomiR** [comment]
On sierra, that will fix the error for me. But it does not complete `yarn run scriptName` but will repeat 1-level arguments. e.g. `yarn run [run, cache, etc]`

**Comment by dsifford** [comment]
Hmm... Might just have to maintain two separate versions of the completion script when time allows.

**Comment by dsifford** [comment]
Nevermind. Looks like others beat me to the punch: https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn

I'll update the readme shortly.

**Comment by duro** [comment]
@dsifford Just heads up, those zsh-completions are giving me trouble as well (before you go all out recommending them). I filed an issue with them here: zsh-users/zsh-completions/issues/519
